name: Update cmd.txt with random string

on:
  workflow_dispatch:

jobs:
  update-cmd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate random string and update cmd.txt
        run: |
          RANDOM_STR=$(openssl rand -hex 6 | tr 'a-f' 'A-F')
          echo "REBOOT_NOW $RANDOM_STR" > cmd.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cmd.txt
          git commit -m "Update cmd.txt with random string"
          git push
